/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ArticlesLeRoiEtLeGenieRouteImport } from './routes/articles.le-roi-et-le-genie'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ArticlesLeRoiEtLeGenieRoute = ArticlesLeRoiEtLeGenieRouteImport.update({
  id: '/le-roi-et-le-genie',
  path: '/le-roi-et-le-genie',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/videos': typeof VideosRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/videos': typeof AdminVideosRoute
  '/articles/le-roi-et-le-genie': typeof ArticlesLeRoiEtLeGenieRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/videos': typeof VideosRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/videos': typeof AdminVideosRoute
  '/articles/le-roi-et-le-genie': typeof ArticlesLeRoiEtLeGenieRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/videos': typeof VideosRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/videos': typeof AdminVideosRoute
  '/articles/le-roi-et-le-genie': typeof ArticlesLeRoiEtLeGenieRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/collections'
    | '/videos'
    | '/admin/articles'
    | '/admin/videos'
    | '/articles/le-roi-et-le-genie'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/auth'
    | '/collections'
    | '/videos'
    | '/admin/articles'
    | '/admin/videos'
    | '/articles/le-roi-et-le-genie'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/collections'
    | '/videos'
    | '/admin/articles'
    | '/admin/videos'
    | '/articles/le-roi-et-le-genie'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthRoute: typeof AuthRoute
  CollectionsRoute: typeof CollectionsRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/articles/le-roi-et-le-genie': {
      id: '/articles/le-roi-et-le-genie'
      path: '/le-roi-et-le-genie'
      fullPath: '/articles/le-roi-et-le-genie'
      preLoaderRoute: typeof ArticlesLeRoiEtLeGenieRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesLeRoiEtLeGenieRoute: typeof ArticlesLeRoiEtLeGenieRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesLeRoiEtLeGenieRoute: ArticlesLeRoiEtLeGenieRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthRoute: AuthRoute,
  CollectionsRoute: CollectionsRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
